### ISSUE TITLE
Not Able to access the APK file

### ISSUE THREAD

**Issue by yashksaini-coder** [Dharmendeer/Cipher-text-apk#1]
@Dharmendeer 
### I am having problem when accessing the APK file for the Cipher-text-apk.###
![image](https://github.com/Dharmendeer/Cipher-text-apk/assets/115717039/422f63a2-bf88-499b-aaaf-bb60c132fe54)

**_Please resolve this as soon as possible!_**
![image](https://github.com/Dharmendeer/Cipher-text-apk/assets/115717039/13a170a7-8e02-4d66-a40f-7080d318d6d8)

**Comment by Dharmendeer** [comment]
Your problem is solved now. You can access that
